package com.wangtingzheng.myorm.enums;

/**
 * @author WangTingZheng
 * @date 2020/7/8 14:14
 * @features
 */
public enum  ItemTypeEnum {
    TINYINT,SMALLINT,INTEGER,BIGINT,FLOAT,DOUBLE,DECIMAL,
    DATE,TIME,YEAR,DATETIME,TIMESTAMP,
    CHAR,VARCHAR,TINYBLOB,TINYTEXT,BLOB,TEXT,MEDIUMBLOB,MEDIUMTEXT,LONGBLOB,LONGTEXT;
}